# Generated by Django 2.2.19 on 2021-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Company_ID:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=models.IntegerField(verbose_name='Zipcode:'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='ccid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Contractor_ID:'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='zipcode',
            field=models.IntegerField(max_length=15, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.FloatField(),
        ),
    ]
